### ISSUE TITLE
Ambiente de testes - Sandbox postback

### ISSUE THREAD

**Issue by devsimoes** [Monetizze/ExemploPOSTCallback#25]
Olá, estou desenvolvendo um aplicativo de notificações e estou usando o postback da Monetizze. Estou com problemas para testar o aplicativo pois não possuo um produto cadastrado na Monetizze e o cliente que solicitou a aplicação também não possui. Dessa forma, não consigo testar o aplicativo, não quero cadastrar um produto na plataforma para testes, pois sei que será reprovado. Como faço para testar o postback além do botão "teste" na plataforma ?

**Comment by ErickVal** [comment]
Boa noite,
A melhor forma de testar não só postback da monetizze, mas vários sistemas (API/WebHook) é utilizando estas duas ferramentas:

- POSTMAN: Para realizar requisições
- Requestbin (https://requestbin.com/): Quando você quer ver detalhes da requisição que você faz.

No seu caso a principio postman é a solução.

**Comment by devsimoes** [comment]
Nossa, muito obrigado! Ainda não tinha trabalhado com webhook, e por conta disso não conhecia as ferramentas acima.

**Comment by arthurbarros** [comment]
@ErickVal é possivel disponibilizar os testes pronto no POSTMAN? estou enfrentando uma dificuldade grande por não estar claro a estrutura do POST que a monetizze envia para o endpoint

**Comment by ErickVal** [comment]
@arthurbarros 

Ele envia um POST com header
content-type: application/x-www-form-urlencode

Para configurar no postman fica assim:
https://i.imgur.com/iBG7te1.png

aí só seguir os campos do Git.
